before_script:
  - npm install -g axios
  - npm ls
language: node_js
node_js:
  - lts/*
os:
  - linux
  # - osx
  # - windows
script:
  - npm run test:package
  - npm run test:unit
  - export DEBUG=testing:*
  - npm run test:integration