before_script:
  - npm install -g axios
  - npm ls
language: node_js
node_js:
  - lts/*
  - '12'
  - '14'
  - '16'
os:
  - linux
script:
  - 'npm run test:package'
  - 'npm run test:unit'
  - 'export DEBUG=testing:*'
  - 'npm run test:integration'
